- hosts:
    - all

  become: yes
  become_user: root
  become_method: sudo

  #remote_user: "{{ lookup('env','ANSIBLE_REMOTE_USER') | default('ansible-tower') }}"
  remote_user: "ansible-tower"
  #strategy: free

  roles:
    - { role: db-software-19c, tags: ['db-software-19c'] }
    - { role: upgradeDB, tags: ['upgradeDB'] }
